### ISSUE TITLE
Edit home page content

### ISSUE THREAD

**Issue by gilestur** [alixedi/cdps#7]
The CDPS Knowledge Hub exists to provide Welsh public sector staff access to:

* common service standards around digital transformation
* best practice advice
* current digital transformation activities

This is a prototype. We're building it in the open, and we welcome contributions from the community.

For starters, you can tell us:

* what you think the Knowledge Hub should do
* what content or topics you'd like to see included
* about changes you'd like to suggest 

**[Make a suggestion or comment](https://github.com/alixedi/knowledge-hub/issues/new).**

**[View the list of existing suggestions](https://github.com/alixedi/knowledge-hub/issues).**

We are using a third party service called GitHub to build this prototype. You will need to sign in to GitHub in order to make a suggestion.

If you'd prefer, you can send suggestions by email to: info@digitalpublicservices.gov.wales

**Comment by alixedi** [comment]
Fixed @gilestur :)
